/*
 * Login.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;

import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.WindowConstants;

import bean.User;

import javax.swing.JOptionPane;

import dao.UserDao;
import util.Dbutil;

/**
 *
 * @author  __USER__
 */
public class Login extends JFrame {

	/** Creates new form Login */
	public Login() {
		super("µÇÂ½");
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new JLabel();
		jLabel2 = new JLabel();
		jLabel3 = new JLabel();
		jTextField1 = new JTextField();
		jButton1 = new JButton();
		jButton2 = new JButton();
		jPasswordField1 = new JPasswordField();

		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("ºÚÌå", 2, 24));
		jLabel1.setForeground(new java.awt.Color(255, 51, 0));
		jLabel1.setText("Î÷µçÐ£Ô°\u4e8c\u624b\u4ea4\u6613\u5e73\u53f0");

		jLabel2.setText("\u7528\u6237\u540d");

		jLabel3.setText("\u5bc6\u7801");

		jButton1.setText("\u767b\u5f55");
		jButton1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("\u6ce8\u518c");
		jButton2.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		GroupLayout layout = new GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		
		layout.setHorizontalGroup(layout
						.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addContainerGap(97, Short.MAX_VALUE)
								.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 268, GroupLayout.PREFERRED_SIZE)
								.addGap(36, 36, 36))
						.addGroup(layout
										.createSequentialGroup()
										.addGap(81, 81, 81)
										.addGroup(layout
														.createParallelGroup(GroupLayout.Alignment.LEADING)
														.addComponent(jLabel2)
														.addComponent(jLabel3))
										.addGap(27, 27, 27)
										.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
														.addComponent(jPasswordField1, 0, 0, Short.MAX_VALUE)
														.addComponent(jTextField1, GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
										.addContainerGap(98, Short.MAX_VALUE))
						.addGroup(layout
										.createSequentialGroup()
										.addGap(114, 114, 114)
										.addComponent(jButton1)
										.addGap(34, 34, 34)
										.addComponent(jButton2)
										.addContainerGap(139, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
									.createParallelGroup(GroupLayout.Alignment.LEADING)
									.addGroup(layout
										.createSequentialGroup()
										.addGap(46, 46, 46)
										.addComponent(jLabel1)
										.addGap(27, 27, 27)
										.addGroup(layout
														.createParallelGroup(GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(layout
														.createParallelGroup( GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(jPasswordField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
										.addGap(34, 34, 34)
										.addGroup(layout
														.createParallelGroup(GroupLayout.Alignment.BASELINE)
														.addComponent(jButton1)
														.addComponent(jButton2))
										.addContainerGap(55, Short.MAX_VALUE)));

		pack();
	}

	private void jButton2ActionPerformed(ActionEvent evt) {
		RegisterUser registerUser=new RegisterUser();
		registerUser.setVisible(true);
		this.dispose();
	}

	private void jButton1ActionPerformed(ActionEvent evt) {
		if ("".equals(jTextField1.getText()) || null == jTextField1.getText()) {
			JOptionPane.showMessageDialog(null, "ÕËºÅ²»ÄÜÎª¿Õ");
			return;
		}
		Dbutil dbutil = new Dbutil();
		User user = new User(jTextField1.getText(), jPasswordField1.getText());
		try {
			Connection connection = dbutil.getCon();
			UserDao userDao = new UserDao();
			if (userDao.login(connection, user)) {
				MainFrom mainFrom=new MainFrom();
				
				mainFrom.setVisible(true);
				mainFrom.setUser(user);
				dispose();
			} else {
				JOptionPane.showMessageDialog(null, "ÕËºÅ»òÃÜÂë´íÎó");
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Login().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private JButton jButton1;
	private JButton jButton2;
	private JLabel jLabel1;
	private JLabel jLabel2;
	private JLabel jLabel3;
	private JPasswordField jPasswordField1;
	private JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}