/*
 * MainFrom.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import javax.swing.JDesktopPane;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.swing.GroupLayout;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

import bean.User;

/**
 *
 * @author  __USER__
 */
public class MainFrom extends JFrame {

	/** Creates new form MainFrom */
	User user = new User();

	public MainFrom() {
		initComponents();
		Shopping shopping = new Shopping(user);
		shopping.setVisible(true);
		shopping.f1 = this;
		jDesktopPane1.add(shopping);
		this.setVisible(true);
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public void createcomadd(String s) {
		CommAdd commAdd = new CommAdd(s);
		commAdd.setVisible(true);
		jDesktopPane1.add(commAdd);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jDesktopPane1 = new JDesktopPane();
		jMenuBar1 = new JMenuBar();
		jMenu1 = new JMenu();
		jMenu3 = new JMenu();
		jMenu4 = new JMenu();
		jMenu5 = new JMenu();
		jMenu6 = new JMenu();
		jMenu8 = new JMenu();
		jMenu9 = new JMenu();
		jMenu7 = new JMenu();
		jMenu10 = new JMenu();
		jMenu12 = new JMenu();
		jMenu2 = new JMenu();
		jMenu11 = new JMenu();
		jMenu13 = new JMenu();
		jMenu14 = new JMenu();

		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u4e8c\u624b\u4ea4\u6613\u5e73\u53f0");

		jMenu1.setText("\u5f00\u59cb");

		jMenu3.setText("\u4ea4\u6613\u7c7b\u522b\u7ba1\u7406");

		jMenu4.setText("\u6dfb\u52a0\u4ea4\u6613\u7c7b\u578b");
		jMenu4.addMouseListener(new MouseAdapter() {
			public void mouseClicked(MouseEvent evt) {
				jMenu4MouseClicked(evt);
			}
		});
		jMenu4.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				jMenu4ActionPerformed(evt);
			}
		});
		jMenu3.add(jMenu4);

		jMenu5.setText("\u4ea4\u6613\u7c7b\u578b\u7ef4\u62a4");
		jMenu5.addMouseListener(new MouseAdapter() {
			public void mouseClicked(MouseEvent evt) {
				jMenu5MouseClicked(evt);
			}
		});
		jMenu5.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				jMenu5ActionPerformed(evt);
			}
		});
		jMenu3.add(jMenu5);

		jMenu1.add(jMenu3);

		jMenu6.setText("\u4ea4\u6613\u7ba1\u7406");

		jMenu8.setText("\u6dfb\u52a0\u4ea4\u6613\u5546\u54c1");
		jMenu8.addMouseListener(new MouseAdapter() {
			public void mouseClicked(MouseEvent evt) {
				jMenu8MouseClicked(evt);
			}
		});
		jMenu6.add(jMenu8);

		jMenu9.setText("\u7ef4\u62a4\u4ea4\u6613\u5546\u54c1");
		jMenu9.addMouseListener(new MouseAdapter() {
			public void mouseClicked(MouseEvent evt) {
				jMenu9MouseClicked(evt);
			}
		});
		jMenu9.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				jMenu9ActionPerformed(evt);
			}
		});
		jMenu6.add(jMenu9);

		jMenu1.add(jMenu6);

		jMenu7.setText("\u8d2d\u4e70\u5546\u54c1");
		jMenu7.addMouseListener(new MouseAdapter() {
			public void mousePressed(MouseEvent evt) {
				jMenu7MousePressed(evt);
			}
		});
		jMenu1.add(jMenu7);

		jMenu10.setText("\u4fee\u6539\u5bc6\u7801");
		jMenu10.addMouseListener(new MouseAdapter() {
			public void mousePressed(MouseEvent evt) {
				jMenu10MousePressed(evt);
			}
		});
		jMenu1.add(jMenu10);

		jMenu12.setText("\u9000\u51fa");
		jMenu12.addMouseListener(new MouseAdapter() {
			public void mousePressed(MouseEvent evt) {
				jMenu12MousePressed(evt);
			}
		});
		jMenu1.add(jMenu12);

		jMenuBar1.add(jMenu1);

		jMenu2.setText("\u9500\u552e\u8bb0\u5f55");

		jMenu11.setText("\u8bb0\u5f55");
		jMenu11.addMouseListener(new MouseAdapter() {
			public void mousePressed(MouseEvent evt) {
				jMenu11MousePressed(evt);
			}
		});
		jMenu2.add(jMenu11);

		jMenuBar1.add(jMenu2);

		jMenu13.setText("\u5173\u4e8e");

		jMenu14.setText("\u5173\u4e8e\u7248\u672c");
		jMenu14.addMouseListener(new MouseAdapter() {
			public void mousePressed(MouseEvent evt) {
				jMenu14MousePressed(evt);
			}
		});
		jMenu13.add(jMenu14);

		jMenuBar1.add(jMenu13);

		setJMenuBar(jMenuBar1);

		GroupLayout layout = new GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				GroupLayout.Alignment.LEADING).addComponent(
				jDesktopPane1, GroupLayout.DEFAULT_SIZE, 854,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addComponent(jDesktopPane1,
						GroupLayout.PREFERRED_SIZE, 574,
						GroupLayout.PREFERRED_SIZE)
						.addContainerGap(47, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jMenu14MousePressed(MouseEvent evt) {
		JOptionPane.showMessageDialog(null, "此版本为 1.0 公测版");
	}

	private void jMenu11MousePressed(MouseEvent evt) {
		SalesRecords salesRecords= new SalesRecords();
		salesRecords.setVisible(true);
		jDesktopPane1.add(salesRecords);
	}

	private void jMenu12MousePressed(MouseEvent evt) {
		dispose();
	}

	private void jMenu7MousePressed(MouseEvent evt) {
		Shopping shopping = new Shopping(user);
		shopping.setVisible(true);
		shopping.f1 = this;
		jDesktopPane1.add(shopping);
	}

	private void jMenu10MousePressed(MouseEvent evt) {
		PasswordManage passwordManage = new PasswordManage(user);
		passwordManage.setVisible(true);
		jDesktopPane1.add(passwordManage);
	}

	private void jMenu9MouseClicked(MouseEvent evt) {
		ComManage comManage = new ComManage();
		comManage.setVisible(true);
		comManage.f = this;
		jDesktopPane1.add(comManage);
	}

	private void jMenu9ActionPerformed(ActionEvent evt) {

	}

	private void jMenu8MouseClicked(MouseEvent evt) {
		CommAdd commAdd = new CommAdd();
		commAdd.setVisible(true);
		jDesktopPane1.add(commAdd);
	}

	private void jMenu5MouseClicked(MouseEvent evt) {
		// TODO add your handling code here:
		ComTypeManage comTypeManage = new ComTypeManage();
		comTypeManage.setVisible(true);
		jDesktopPane1.add(comTypeManage);
	}

	private void jMenu5ActionPerformed(ActionEvent evt) {

	}

	private void jMenu4MouseClicked(MouseEvent evt) {
		TypeFrom typeFrom = new TypeFrom();
		jDesktopPane1.add(typeFrom);
		typeFrom.setVisible(true);
	}

	private void jMenu4ActionPerformed(ActionEvent evt) {
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainFrom().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private JDesktopPane jDesktopPane1;
	private JMenu jMenu1;
	private JMenu jMenu10;
	private JMenu jMenu11;
	private JMenu jMenu12;
	private JMenu jMenu13;
	private JMenu jMenu14;
	private JMenu jMenu2;
	private JMenu jMenu3;
	private JMenu jMenu4;
	private JMenu jMenu5;
	private JMenu jMenu6;
	private JMenu jMenu7;
	private JMenu jMenu8;
	private JMenu jMenu9;
	private JMenuBar jMenuBar1;

	// End of variables declaration//GEN-END:variables

	public void createcomadd(String text, int i) {
		// TODO Auto-generated method stub
		CommAdd commAdd = new CommAdd(text, 1);
		commAdd.setVisible(true);
		jDesktopPane1.add(commAdd);
	}

}