/*
 * PasswordManage.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.SQLException;

import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

import bean.User;

import javax.swing.JOptionPane;

import dao.UserDao;
import util.Dbutil;

/**
 *
 * @author  __USER__
 */
public class PasswordManage extends JInternalFrame {
	User user = new User();

	/** Creates new form PasswordManage */
	public PasswordManage() {
		initComponents();
	}

	public PasswordManage(User user) {
		initComponents();
		this.user = user;
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new JLabel();
		jLabel2 = new JLabel();
		jLabel3 = new JLabel();
		jTextField1 = new JTextField();
		jPasswordField1 = new JPasswordField();
		jPasswordField2 = new JPasswordField();
		jButton1 = new JButton();
		jButton2 = new JButton();

		setClosable(true);
		setIconifiable(true);

		jLabel1.setText("\u65e7\u5bc6\u7801");

		jLabel2.setText("\u65b0\u5bc6\u7801");

		jLabel3.setText("\u65b0\u5bc6\u7801");

		jButton1.setText("\u4fee\u6539");
		jButton1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("\u53d6\u6d88");
		jButton2.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		GroupLayout layout = new GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(95, 95, 95)
										.addGroup(
												layout
														.createParallelGroup(
																GroupLayout.Alignment.TRAILING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jButton1)
																		.addGap(
																				57,
																				57,
																				57)
																		.addComponent(
																				jButton2))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel1)
																						.addComponent(
																								jLabel2)
																						.addComponent(
																								jLabel3))
																		.addGap(
																				34,
																				34,
																				34)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								jPasswordField2,
																								0,
																								0,
																								Short.MAX_VALUE)
																						.addComponent(
																								jPasswordField1)
																						.addComponent(
																								jTextField1,
																								GroupLayout.PREFERRED_SIZE,
																								134,
																								GroupLayout.PREFERRED_SIZE))))
										.addContainerGap(102, Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(44, 44, 44)
										.addGroup(
												layout
														.createParallelGroup(
																GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																jTextField1,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE))
										.addGap(42, 42, 42)
										.addGroup(
												layout
														.createParallelGroup(
																GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(
																jPasswordField1,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE))
										.addGap(52, 52, 52)
										.addGroup(
												layout
														.createParallelGroup(
																GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(
																jPasswordField2,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE))
										.addGap(44, 44, 44)
										.addGroup(
												layout
														.createParallelGroup(
																GroupLayout.Alignment.BASELINE)
														.addComponent(jButton1)
														.addComponent(jButton2))
										.addContainerGap(50, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(ActionEvent evt) {
		if(jTextField1.getText().equals(user.getPassword()))
		{
			if((jPasswordField1.getText().equals(jPasswordField2.getText()) ))
				if(jPasswordField1.getText()!=null) 
				if((jPasswordField1.getText().equals(""))==false )
				{
					user.setPassword(jPasswordField1.getText());
					Dbutil dbutil=new Dbutil();
					Connection connection=null;
					UserDao userDao=new UserDao();
					try {
						connection=dbutil.getCon();
						if(userDao.userupdate(connection, user)==1)
						{
							JOptionPane.showMessageDialog(null, "修改成功");
							return ;
						}
					} catch (Exception e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
						JOptionPane.showMessageDialog(null, e.getMessage());
					}finally{
						try {
							connection.close();
						} catch (SQLException e) {
							// TODO Auto-generated catch block
							e.printStackTrace();
						}
					}
					
					
					return ;
				}
		}
		JOptionPane.showMessageDialog(null, "密码输入错误");
	}

	private void jButton2ActionPerformed(ActionEvent evt) {
		dispose();
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private JButton jButton1;
	private JButton jButton2;
	private JLabel jLabel1;
	private JLabel jLabel2;
	private JLabel jLabel3;
	private JPasswordField jPasswordField1;
	private JPasswordField jPasswordField2;
	private JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}