/*
 * RegisterUser.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;

import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;

import bean.User;

import javax.swing.JOptionPane;

import dao.UserDao;
import util.Dbutil;



/**
 *
 * @author  __USER__
 */
public class RegisterUser extends JFrame {

	/** Creates new form RegisterUser */
	public RegisterUser() {
		super("用户注册");
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new JLabel();
		jLabel2 = new JLabel();
		jLabel3 = new JLabel();
		jTextField1 = new JTextField();
		jTextField2 = new JTextField();
		jTextField3 = new JTextField();
		jButton1 = new JButton();
		jButton2 = new JButton();

		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("\u7528\u6237\u540d");

		jLabel2.setText("\u5bc6\u7801");

		jLabel3.setText("\u518d\u6b21\u8f93\u5165\u5bc6\u7801");

		jButton1.setText("\u6ce8\u518c");
		jButton1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("\u53d6\u6d88");
		jButton2.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		GroupLayout layout = new GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		
		layout.setHorizontalGroup(layout
						.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(layout
										.createSequentialGroup()
										.addGap(69, 69, 69)
										.addGroup(layout
														.createParallelGroup(GroupLayout.Alignment.LEADING)
														.addGroup(layout
																		.createSequentialGroup()
																		.addGap(35,35,35)
																		.addComponent(jButton1)
																		.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(jButton2)
																		.addContainerGap())
														.addGroup(layout
																		.createSequentialGroup()
																		.addGroup(layout
																						.createParallelGroup(GroupLayout.Alignment.LEADING)
																						.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 61, GroupLayout.PREFERRED_SIZE)
																						.addComponent(jLabel2)
																						.addComponent(jLabel3))
																		.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
																		.addGroup(layout
																						.createParallelGroup(GroupLayout.Alignment.LEADING, false)
																						.addComponent(jTextField3)
																						.addComponent(jTextField2)
																						.addGroup(layout
																										.createSequentialGroup()
																										.addComponent(jTextField1, GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
																										.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)))
																		.addContainerGap(83, GroupLayout.PREFERRED_SIZE)))));
		
		layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(layout
										.createSequentialGroup()
										.addGap(40, 40, 40)
										.addGroup(layout
														.createParallelGroup(GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
														.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(layout
														.createParallelGroup(GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(layout
														.createParallelGroup(GroupLayout.Alignment.LEADING)
														.addComponent(jLabel3)
														.addComponent(jTextField3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
										.addGap(28, 28, 28)
										.addGroup(layout
														.createParallelGroup(GroupLayout.Alignment.BASELINE)
														.addComponent(jButton2)
														.addComponent(jButton1))
										.addContainerGap(72, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(ActionEvent evt) {
		if(jTextField1.getText().equals("")==false || jTextField1.getText()!="")
		{	if(jTextField2.getText().equals(jTextField3.getText()))
			{
				Dbutil dbutil=new Dbutil();
				User user=new User(jTextField1.getText(),jTextField2.getText());
				try {
					Connection connection=dbutil.getCon();
					UserDao userDao=new UserDao();
					if(userDao.register(connection, user)==1)
					{
						JOptionPane.showMessageDialog(null, "注册成功");
						Login login=new Login();
						login.setVisible(true);
						this.dispose();
						return ;
					}
					else {
						JOptionPane.showMessageDialog(null, "注册失败,可能是用户名已经存在");
						return ;
					}
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
					JOptionPane.showMessageDialog(null, "注册失败,可能是用户名已经存在");
					return ;
				}
			}
		}
		JOptionPane.showMessageDialog(null, "用户名为空或者密码不正确");
		
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		this.dispose();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new RegisterUser().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private JButton jButton1;
	private JButton jButton2;
	private JLabel jLabel1;
	private JLabel jLabel2;
	private JLabel jLabel3;
	private JTextField jTextField1;
	private JTextField jTextField2;
	private JTextField jTextField3;
	// End of variables declaration//GEN-END:variables

}