/*
 * SalesRecords.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import dao.SalesReDao;
import util.Dbutil;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;

import javax.swing.GroupLayout;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.LayoutStyle;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  __USER__
 */
public class SalesRecords extends JInternalFrame {
	Connection connection = null;
	Dbutil dbutil = new Dbutil();
	SalesReDao salesReDao = new SalesReDao();
	float total = 0;

	/** Creates new form SalesRecords */
	public SalesRecords() {
		initComponents();
		filltable1();
	}

	private void filltable1() {
		DefaultTableModel defaultTableModel = (DefaultTableModel) jTable1
		.getModel();
		defaultTableModel.setRowCount(0);
		try {
			connection = dbutil.getCon();
			ResultSet resultSet = salesReDao.getResultSet(connection);
			while (resultSet.next()) {
				Vector a = new Vector();
				a.add(resultSet.getInt(1));
				a.add(resultSet.getString(2));
				a.add(resultSet.getInt(3));
				total += resultSet.getFloat(4);
				a.add(resultSet.getFloat(4));
				a.add(resultSet.getInt(5));
				defaultTableModel.addRow(a);
			}
			jLabel2.setText("" + total);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getMessage());
		} finally {
			try {
				connection.close();
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	@SuppressWarnings("serial")
	private void initComponents() {

		jScrollPane1 = new JScrollPane();
		jTable1 = new JTable();
		jLabel1 = new JLabel();
		jLabel2 = new JLabel();

		setClosable(true);
		setIconifiable(true);

		jTable1.setModel(new DefaultTableModel(
			new Object[][] {}, new String[] { "id", "商品名", "数量", "总价", "日期" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false,
				true };

				public boolean isCellEditable(int rowIndex, int columnIndex) {
					return canEdit[columnIndex];
				}
			});
		jScrollPane1.setViewportView(jTable1);

		jLabel1.setText("\u603b\u8ba1");

		GroupLayout layout = new GroupLayout(
			getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
			.createParallelGroup(
				GroupLayout.Alignment.LEADING)
			.addGroup(
				layout
				.createSequentialGroup()
				.addGroup(
					layout
					.createParallelGroup(
						GroupLayout.Alignment.LEADING)
					.addGroup(
						layout
						.createSequentialGroup()
						.addGap(66, 66, 66)
						.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 616, GroupLayout.PREFERRED_SIZE))
					.addGroup(
						layout
						.createSequentialGroup()
						.addGap(188, 188, 188)
						.addComponent(jLabel1)
						.addGap(60, 60, 60)
						.addComponent(jLabel2)))
				.addContainerGap(59, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
			.createParallelGroup(GroupLayout.Alignment.LEADING)
			.addGroup(
				GroupLayout.Alignment.TRAILING,
				layout
				.createSequentialGroup()
				.addContainerGap(25, Short.MAX_VALUE)
				.addGroup(
					layout
					.createParallelGroup(GroupLayout.Alignment.BASELINE)
					.addComponent(jLabel1)
					.addComponent(jLabel2))
				.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
				.addComponent(
					jScrollPane1,
					GroupLayout.PREFERRED_SIZE,
					321,
					GroupLayout.PREFERRED_SIZE)
				.addGap(32, 32, 32)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private JLabel jLabel1;
	private JLabel jLabel2;
	private JScrollPane jScrollPane1;
	private JTable jTable1;
	// End of variables declaration//GEN-END:variables

}